package de.mephisto.vpin.restclient.validation;

public interface GameValidationCode {
  int CODE_NO_ROM = 1;
  int CODE_ROM_NOT_EXISTS = 3;
  int CODE_VPX_NOT_EXISTS = 4;
  int CODE_NVOFFSET_MISMATCH = 5;
  int CODE_ROM_INVALID = 6;
  int CODE_VR_DISABLED = 7;

  int CODE_SCREEN_SIZE_ISSUE = 10;

  int CODE_NO_DIRECTB2S_OR_PUPPACK = 20;
  int CODE_NO_DIRECTB2S_AND_PUPPACK_DISABLED = 21;
  int CODE_NO_DMDFOLDER = 22;
  int CODE_BACKGLASS_AND_BACKGLASSES_DISABLED = 23;

  int CODE_NO_AUDIO = 30;
  int CODE_NO_AUDIO_LAUNCH = 31;
  int CODE_NO_APRON = 32;
  int CODE_NO_INFO = 33;
  int CODE_NO_HELP = 34;
  int CODE_NO_TOPPER = 35;
  int CODE_NO_BACKGLASS = 36;
  int CODE_NO_DMD = 37;
  int CODE_NO_PLAYFIELD = 38;
  int CODE_NO_LOADING = 39;
  int CODE_NO_OTHER2 = 40;
  int CODE_NO_WHEEL_IMAGE = 41;
  int CODE_NO_LOGO = 42;

  int CODE_ALT_SOUND_NOT_ENABLED = 50;
  int CODE_ALT_SOUND_FILE_MISSING = 51;
  int CODE_FORCE_STEREO = 52;

  int CODE_PUP_PACK_FILE_MISSING = 60;

  int CODE_VPS_MAPPING_MISSING = 70;
  int CODE_VPS_ALTCOLOR_MISSING = 71;
  int CODE_VPS_ALTSOUND_MISSING = 72;
  int CODE_VPS_PUPPACK_MISSING = 73;

  int CODE_ALT_COLOR_COLORIZE_DMD_ENABLED = 80;
  int CODE_ALT_COLOR_EXTERNAL_DMD_NOT_ENABLED = 81;
  int CODE_ALT_COLOR_FILES_MISSING = 82;
  int CODE_ALT_COLOR_DMDDEVICE_FILES_MISSING = 84;

  int CODE_SCRIPT_CONTROLLER_STOP_MISSING = 90;
  int CODE_SCRIPT_FILES_MISSING = 91;
}
