package de.mephisto.vpin.restclient.jobs;

public enum JobType {
  TABLE_BACKUP,
  TABLE_IMPORT,
  PUP_INSTALL,
  POV_INSTALL,
  DIRECTB2S_INSTALL,
  ALTSOUND_INSTALL,
  POPPER_MEDIA_INSTALL,
  PLAYLIST_MEDIA_INSTALL,
  ALTCOLOR_INSTALL,
  DOF_SYNC,
  RECORDER,
  ARCHIVE_INSTALL,
  ARCHIVE_DOWNLOAD_TO_FILESYSTEM,
}
