package de.mephisto.vpin.restclient.jobs;

public enum JobType {
  TABLE_BACKUP,
  TABLE_IMPORT,
  PUP_INSTALL,
  POV_INSTALL,
  DIRECTB2S_INSTALL,
  ALTSOUND_INSTALL,
  ARCHIVE_INSTALL,
  ARCHIVE_BUNDLING,
  ARCHIVE_DOWNLOAD_TO_FILESYSTEM,
  ARCHIVE_DOWNLOAD_TO_REPOSITORY,
}
