# Launch4j runtime config
-Dfile.encoding=utf-8
--add-exports=javafx.graphics/com.sun.javafx.iio=ALL-UNNAMED
--add-exports=javafx.graphics/com.sun.javafx.iio.common=ALL-UNNAMED
--enable-native-access=javafx.graphics
#-Duser.country=US
#-Duser.language=en